spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatdb


  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8081
  servlet:
    jsp:
      init-parameters: true





