spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatdb

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false

server:
  port: 8081

